apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: quote-api
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090
        access: proxy
        isDefault: true
