apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: quote-api
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: 'quote-api'
        metrics_path: /metrics
        static_configs:
          - targets: ["quote-api-service.quote-api.svc.cluster.local:80"]
