apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-api
  namespace: quote-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote-api
  template:
    metadata:
      labels:
        app: quote-api
    spec:
      containers:
        - name: quote-api
          image: jeeffry/quote-api:1.1 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet: { path: /healthz, port: 5000 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 5000 }
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: QUOTES_PATH
              value: "/app/quotes.json"
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits:   { cpu: "250m", memory: "256Mi" }

