apiVersion: v1
kind: Service
metadata:
  name: quote-api-service
  namespace: quote-api
spec:
  selector:
    app: quote-api
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: NodePort
